// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtCa5R6wTJmExQYsy5dZy6va_KVjisNa4',
    appId: '1:306964986810:web:42308c917bda26f5bf3b83',
    messagingSenderId: '306964986810',
    projectId: 'school-2c901',
    authDomain: 'school-2c901.firebaseapp.com',
    storageBucket: 'school-2c901.appspot.com',
    measurementId: 'G-9JDLRX5W29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK8XtF9ARn5iqeY56Vmp41ZHqR_JEpwII',
    appId: '1:306964986810:android:a45dcec4a84b7520bf3b83',
    messagingSenderId: '306964986810',
    projectId: 'school-2c901',
    storageBucket: 'school-2c901.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9tWSVux2_Q4ZvqU2a9oY5Utm0czRuCV4',
    appId: '1:306964986810:ios:ab0a5d3c6ea5564dbf3b83',
    messagingSenderId: '306964986810',
    projectId: 'school-2c901',
    storageBucket: 'school-2c901.appspot.com',
    iosBundleId: 'com.global.ischool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9tWSVux2_Q4ZvqU2a9oY5Utm0czRuCV4',
    appId: '1:306964986810:ios:ab0a5d3c6ea5564dbf3b83',
    messagingSenderId: '306964986810',
    projectId: 'school-2c901',
    storageBucket: 'school-2c901.appspot.com',
    iosBundleId: 'com.global.ischool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtCa5R6wTJmExQYsy5dZy6va_KVjisNa4',
    appId: '1:306964986810:web:93f6d39fbf971e6dbf3b83',
    messagingSenderId: '306964986810',
    projectId: 'school-2c901',
    authDomain: 'school-2c901.firebaseapp.com',
    storageBucket: 'school-2c901.appspot.com',
    measurementId: 'G-K8XKXWW8HS',
  );

}